import type {
  SchoolBookingAssignment,
  SchoolInstructorRosterItem,
  SchoolOperationsProfile,
  SchoolPackageDefinition,
  SchoolRescheduleSlot,
  SchoolVehicle,
  SchoolVerificationDocument,
} from "@/types";

export const schoolOperationsProfile: SchoolOperationsProfile = {
  id: "school-elite-safety",
  name: "Elite Safety Driving Academy",
  initials: "ES",
  adminName: "Adewale Martins",
  verificationStatus: "approved",
  frscRegistrationNumber: "FRSC/DS/ABJ/2026/1048",
  primaryLocation: "Wuse II, Abuja",
  email: "operations@elitesafety.ng",
  phone: "+234 809 555 0188",
  addressLine1: "18 Aminu Kano Crescent",
  addressLine2: null,
  city: "Abuja",
  state: "FCT",
  country: "Nigeria",
  address: "18 Aminu Kano Crescent, Wuse II, Abuja",
  description:
    "FRSC-verified driving instruction focused on safe, confident, and responsible road use.",
  operatingAreas: ["Wuse II", "Maitama", "Garki"],
  assignmentPolicy: "learner_preference",
  activeInstructors: 3,
  pendingInvites: 2,
  activeBookings: 18,
  vehicles: 6,
  packages: 4,
};

export const schoolInstructorRoster: SchoolInstructorRosterItem[] = [
  {
    id: "instructor-john",
    firstName: "John",
    lastName: "Adeyemi",
    name: "John Adeyemi",
    initials: "JA",
    email: "john.ade@example.com",
    phone: "+234 803 555 0142",
    status: "active",
    assignedLocation: "Wuse II Training Yard",
    allowedTransmissions: ["automatic", "manual"],
    invitedAt: "2026-05-12T10:00:00.000Z",
    activatedAt: "2026-05-15T09:20:00.000Z",
    lessonsThisWeek: 14,
  },
  {
    id: "instructor-grace",
    firstName: "Grace",
    lastName: "Okafor",
    name: "Grace Okafor",
    initials: "GO",
    email: "grace.okafor@example.com",
    phone: "+234 809 140 2210",
    status: "active",
    assignedLocation: "Maitama Route",
    allowedTransmissions: ["automatic"],
    invitedAt: "2026-05-18T09:00:00.000Z",
    activatedAt: "2026-05-21T11:45:00.000Z",
    lessonsThisWeek: 9,
  },
  {
    id: "instructor-chinedu",
    firstName: "Chinedu",
    lastName: "Nwosu",
    name: "Chinedu Nwosu",
    initials: "CN",
    email: "chinedu.nwosu@example.com",
    phone: "+234 802 778 1091",
    status: "pending",
    assignedLocation: "Garki Route",
    allowedTransmissions: ["manual"],
    invitedAt: "2026-06-28T12:00:00.000Z",
    activatedAt: null,
    lessonsThisWeek: 0,
  },
  {
    id: "instructor-amina",
    firstName: "Amina",
    lastName: "Bello",
    name: "Amina Bello",
    initials: "AB",
    email: "amina.bello@example.com",
    phone: "+234 806 412 9001",
    status: "invited",
    assignedLocation: "Wuse II Training Yard",
    allowedTransmissions: ["automatic", "manual"],
    invitedAt: "2026-07-01T09:30:00.000Z",
    activatedAt: null,
    lessonsThisWeek: 0,
  },
];

export const schoolVehicles: SchoolVehicle[] = [
  {
    id: "vehicle-corolla",
    schoolId: "school-elite-safety",
    make: "Toyota",
    model: "Corolla",
    year: 2022,
    plateNumber: "ABJ-482-KWL",
    color: "Silver",
    transmissionType: "automatic",
    isActive: true,
    name: "Toyota Corolla",
    assignedLocation: "Wuse II Training Yard",
    lastInspectionAt: "2026-06-20T09:00:00.000Z",
    lessonsThisWeek: 18,
  },
  {
    id: "vehicle-yaris",
    schoolId: "school-elite-safety",
    make: "Toyota",
    model: "Yaris",
    year: 2021,
    plateNumber: "ABJ-913-KJA",
    color: "White",
    transmissionType: "manual",
    isActive: true,
    name: "Toyota Yaris",
    assignedLocation: "Wuse II Training Yard",
    lastInspectionAt: "2026-06-17T11:30:00.000Z",
    lessonsThisWeek: 12,
  },
  {
    id: "vehicle-civic",
    schoolId: "school-elite-safety",
    make: "Honda",
    model: "Civic",
    year: 2020,
    plateNumber: "ABJ-225-GRK",
    color: "Black",
    transmissionType: "automatic",
    isActive: false,
    name: "Honda Civic",
    assignedLocation: "Maitama Route",
    lastInspectionAt: "2026-06-02T13:00:00.000Z",
    lessonsThisWeek: 0,
  },
];

export const schoolPackageDefinitions: SchoolPackageDefinition[] = [
  {
    id: "package-road-ready",
    schoolId: "school-elite-safety",
    name: "Road Ready Starter",
    description:
      "Core controls, road signs, parking, and supervised city practice.",
    price: 45000,
    currency: "NGN",
    numberOfLessons: 6,
    durationInDays: 21,
    isActive: true,
    eligibleTransmissions: ["automatic", "manual"],
    purchasesThisMonth: 21,
  },
  {
    id: "package-defensive-pro",
    schoolId: "school-elite-safety",
    name: "Defensive Driving Pro",
    description:
      "Hazard awareness, highway confidence, and emergency manoeuvres.",
    price: 78500,
    currency: "NGN",
    numberOfLessons: 10,
    durationInDays: 35,
    isActive: true,
    eligibleTransmissions: ["automatic", "manual"],
    purchasesThisMonth: 14,
  },
  {
    id: "package-auto-city",
    schoolId: "school-elite-safety",
    name: "Automatic City Confidence",
    description: "Focused city-driving practice for automatic vehicles.",
    price: 52000,
    currency: "NGN",
    numberOfLessons: 7,
    durationInDays: 28,
    isActive: false,
    eligibleTransmissions: ["automatic"],
    purchasesThisMonth: 0,
  },
];

export const schoolBookingAssignments: SchoolBookingAssignment[] = [
  {
    id: "booking-amara-04",
    learnerName: "Amara Okeke",
    learnerInitials: "AO",
    packageName: "Road Ready Starter",
    lessonNumber: 4,
    totalLessons: 6,
    scheduledAt: "2026-07-14T09:00:00.000Z",
    location: "Wuse II Training Yard",
    transmission: "automatic",
    instructorPreferenceId: "instructor-grace",
    instructorId: null,
    vehicleId: null,
    status: "unassigned",
    requestedAt: "2026-07-11T15:20:00.000Z",
    rescheduledAt: null,
    cancellationReason: null,
    cancelledAt: null,
  },
  {
    id: "booking-daniel-02",
    learnerName: "Daniel Musa",
    learnerInitials: "DM",
    packageName: "Defensive Driving Pro",
    lessonNumber: 2,
    totalLessons: 10,
    scheduledAt: "2026-07-14T12:30:00.000Z",
    location: "Wuse II Training Yard",
    transmission: "manual",
    instructorPreferenceId: null,
    instructorId: "instructor-john",
    vehicleId: "vehicle-yaris",
    status: "assigned",
    requestedAt: "2026-07-10T08:45:00.000Z",
    rescheduledAt: null,
    cancellationReason: null,
    cancelledAt: null,
  },
  {
    id: "booking-zainab-06",
    learnerName: "Zainab Bello",
    learnerInitials: "ZB",
    packageName: "Automatic City Confidence",
    lessonNumber: 6,
    totalLessons: 7,
    scheduledAt: "2026-07-15T10:00:00.000Z",
    location: "Maitama Route",
    transmission: "automatic",
    instructorPreferenceId: "instructor-grace",
    instructorId: "instructor-grace",
    vehicleId: "vehicle-corolla",
    status: "confirmed",
    requestedAt: "2026-07-09T11:10:00.000Z",
    rescheduledAt: null,
    cancellationReason: null,
    cancelledAt: null,
  },
];

export const schoolRescheduleSlots: SchoolRescheduleSlot[] = [
  {
    id: "slot-jul-16-0900",
    scheduledAt: "2026-07-16T09:00:00.000Z",
    label: "Thursday, 16 July · 9:00 AM",
  },
  {
    id: "slot-jul-16-1330",
    scheduledAt: "2026-07-16T13:30:00.000Z",
    label: "Thursday, 16 July · 1:30 PM",
  },
  {
    id: "slot-jul-17-1000",
    scheduledAt: "2026-07-17T10:00:00.000Z",
    label: "Friday, 17 July · 10:00 AM",
  },
];

export const schoolVerificationDocuments: SchoolVerificationDocument[] = [
  {
    type: "frsc_certificate",
    label: "FRSC driving school licence",
    description: "Current approval to operate as a driving school",
    required: true,
    fileName: "frsc-operating-licence.pdf",
    uri: "fixture://frsc-operating-licence.pdf",
    mimeType: "application/pdf",
    size: 1480000,
    uploadedAt: "2026-05-10T09:00:00.000Z",
  },
  {
    type: "business_registration",
    label: "CAC registration certificate",
    description: "Registered business identity and legal name",
    required: true,
    fileName: "cac-certificate.pdf",
    uri: "fixture://cac-certificate.pdf",
    mimeType: "application/pdf",
    size: 920000,
    uploadedAt: "2026-05-10T09:05:00.000Z",
  },
  {
    type: "tax_document",
    label: "Proof of operating address",
    description: "Recent utility bill or tenancy document",
    required: true,
    fileName: "wuse-office-utility.pdf",
    uri: "fixture://wuse-office-utility.pdf",
    mimeType: "application/pdf",
    size: 730000,
    uploadedAt: "2026-05-10T09:10:00.000Z",
  },
  {
    type: "other",
    label: "Administrator identity",
    description: "Government-issued ID for the accountable school admin",
    required: true,
    fileName: "admin-national-id.jpg",
    uri: "fixture://admin-national-id.jpg",
    mimeType: "image/jpeg",
    size: 610000,
    uploadedAt: "2026-05-10T09:15:00.000Z",
  },
  {
    type: "insurance",
    label: "Vehicle insurance",
    description: "Optional fleet insurance evidence",
    required: false,
    fileName: null,
    uri: null,
    mimeType: null,
    size: null,
    uploadedAt: null,
  },
];
